//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Web.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Booking.Web.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Всего:.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Все права защищены.
        /// </summary>
        public static string All_rights_reserved {
            get {
                return ResourceManager.GetString("All_rights_reserved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Расписание всех аудиторий.
        /// </summary>
        public static string AllAudiencesSchedule {
            get {
                return ResourceManager.GetString("AllAudiencesSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Эта аудитория занята на выбранное время. Выберите, пожалуйста другое..
        /// </summary>
        public static string AudienceIsAlreadyBooked {
            get {
                return ResourceManager.GetString("AudienceIsAlreadyBooked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Расписание аудитории.
        /// </summary>
        public static string AudienceSchedule {
            get {
                return ResourceManager.GetString("AudienceSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите отменить событие?.
        /// </summary>
        public static string CancelEventAskMessage {
            get {
                return ResourceManager.GetString("CancelEventAskMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Выберите аудиторию.
        /// </summary>
        public static string ChooseAudience {
            get {
                return ResourceManager.GetString("ChooseAudience", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Повторить пароль.
        /// </summary>
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Сообщения слишком большое, максимальная длина 2000 символов..
        /// </summary>
        public static string ContactViewModel_Message_ValidationMessage {
            get {
                return ResourceManager.GetString("ContactViewModel_Message_ValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Спасибо. Ваше сообщение отправлено администратору..
        /// </summary>
        public static string ContactViewModel_SuccessMessage {
            get {
                return ResourceManager.GetString("ContactViewModel_SuccessMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Неправильный формат имени..
        /// </summary>
        public static string ContactViewModel_UserName_ValidationMessage {
            get {
                return ResourceManager.GetString("ContactViewModel_UserName_ValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Неправильный формат фамилии..
        /// </summary>
        public static string ContactViewModel_UserSurname_ValidationMessage {
            get {
                return ResourceManager.GetString("ContactViewModel_UserSurname_ValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string EmailAddressPlaceholder {
            get {
                return ResourceManager.GetString("EmailAddressPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Укажите email, чтобы присоединится.
        /// </summary>
        public static string EnterEmailToJoin {
            get {
                return ResourceManager.GetString("EnterEmailToJoin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Планируют принять участие {0} человек..
        /// </summary>
        public static string EventPageParticipantsCount {
            get {
                return ResourceManager.GetString("EventPageParticipantsCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Обратная связь.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Этаж.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to На домашнюю страницу.
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-user&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string IconUser {
            get {
                return ResourceManager.GetString("IconUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Неверные данные.
        /// </summary>
        public static string InvalidLoginAttempt_Message {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Присоединиться.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Регистрация желающих.
        /// </summary>
        public static string JoinAvailable {
            get {
                return ResourceManager.GetString("JoinAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginSubmit {
            get {
                return ResourceManager.GetString("LoginSubmit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Напишите, если у вас есть идеи, предложения, замечания или вопросы..
        /// </summary>
        public static string MessageIdea {
            get {
                return ResourceManager.GetString("MessageIdea", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Такой страницы не существует.
        /// </summary>
        public static string NotFound404 {
            get {
                return ResourceManager.GetString("NotFound404", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сейчас.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to или.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Количество активных событий.
        /// </summary>
        public static string NumberOfActiveEvent {
            get {
                return ResourceManager.GetString("NumberOfActiveEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неверный пароль.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Повторить новый пароль.
        /// </summary>
        public static string PasswordNewRepeat {
            get {
                return ResourceManager.GetString("PasswordNewRepeat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string PasswordOld {
            get {
                return ResourceManager.GetString("PasswordOld", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Приватно.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Публично.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Пароль успешно изменен.
        /// </summary>
        public static string PasswordSuccess {
            get {
                return ResourceManager.GetString("PasswordSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Пользователь с такими данными уже существует.
        /// </summary>
        public static string RegisterAction_UserAlreadyExists {
            get {
                return ResourceManager.GetString("RegisterAction_UserAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированные участники.
        /// </summary>
        public static string RegisteredParticipants {
            get {
                return ResourceManager.GetString("RegisteredParticipants", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterSubmit {
            get {
                return ResourceManager.GetString("RegisterSubmit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Пароли не совпадают.
        /// </summary>
        public static string RegisterViewModel_ConfirmPassword_ValidationMessage {
            get {
                return ResourceManager.GetString("RegisterViewModel_ConfirmPassword_ValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Неверный адрес электронной почты.
        /// </summary>
        public static string RegisterViewModel_Email_ValidationMessage {
            get {
                return ResourceManager.GetString("RegisterViewModel_Email_ValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Пароль должен содержать 8-15 символов.
        /// </summary>
        public static string RegisterViewModel_Password_ValidationMessage {
            get {
                return ResourceManager.GetString("RegisterViewModel_Password_ValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Неправильный формат имени и фамилии..
        /// </summary>
        public static string RegisterViewModel_UserName_ValidationMessage {
            get {
                return ResourceManager.GetString("RegisterViewModel_UserName_ValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Регистрация желающих.
        /// </summary>
        public static string RegistrationTo {
            get {
                return ResourceManager.GetString("RegistrationTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Зарезервировать аудиторию.
        /// </summary>
        public static string ReserveAudience {
            get {
                return ResourceManager.GetString("ReserveAudience", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Смена пароля.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Расписание.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Показать автора.
        /// </summary>
        public static string ShowAuthor {
            get {
                return ResourceManager.GetString("ShowAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Указать организатора.
        /// </summary>
        public static string ShowOrganizer {
            get {
                return ResourceManager.GetString("ShowOrganizer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Список пользователей.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Имя Фамилия.
        /// </summary>
        public static string UserNamePlaceholder {
            get {
                return ResourceManager.GetString("UserNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-exclamation-circle&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt; Поле должно быть заполнено..
        /// </summary>
        public static string ValidationMessage_Required {
            get {
                return ResourceManager.GetString("ValidationMessage_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Когда.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Где.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Написать сообщение.
        /// </summary>
        public static string WriteMessage {
            get {
                return ResourceManager.GetString("WriteMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
